name: PR-pipeline

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:

  tfsec-check:
    name: Security Scan (tfsec)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash


      - name: Run tfsec scan
        run: |
          tfsec ./environment/dev 

  


  tflint-check:
    name: Linting Check (tflint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup tflint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: latest
          

      - name: Run tflint
        run: |
          tflint --init
          tflint --chdir=./environment/dev

  terraform-plan:
    name: Terraform Plan + Comment
    runs-on: ubuntu-latest
    needs: [tfsec-check, tflint-check]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./environment/dev

      - name: Terraform Plan
        run: terraform plan -no-color -out=tfplan
        working-directory: ./environment/dev

      - name: Comment Plan on PR
        run: |
          terraform show -no-color tfplan  > plan.txt
          gh pr comment "${{ github.event.pull_request.number }}" --body-file plan.txt || echo "⚠️ Comment failed, but continuing..."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./environment/dev
